name: Update Package Versions Workflow

env:
  GITHUB_TOKEN: ${{ secrets.WRITE_ACCESS_TOKEN }}

on:
  push:
    branches:
      - main

jobs:
  update-package-versions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create and push branch
        env:
          GITHUB_TOKEN: ${{ secrets.WRITE_ACCESS_TOKEN }}
        run: |
          git checkout -b automated-package-version
          git push origin automated-package-version

      - name: Update yarn.lock
        run: node ./scripts/update-package-versions.js
