name: Update Package Versions Workflow

on:
  push:
    branches:
      - main

jobs:
  update-package-versions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create and push branch
        run: |
          git checkout -b automated-package-version
          git push origin automated-package-version

      - name: Update yarn.lock
        run: node ./scripts/update-package-versions.js

      - name: Commit and push changes
        run: |
          git config --local user.email "jmanke@gmail.com"
          git config --local user.name "jmanke"
          git add yarn.lock
          git commit -m "Automated Package Version Update"
          git push origin automated-package-version
