name: Update Package Versions Workflow

on:
  push:
    branches:
      - main

jobs:
  update-package-versions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      # - name: Console log
      #   run: ls
      # - name: Create branch
      #   run: git branch automated-package-update
      # - name: Push branch
      #   run: git push origin automated-package-update

      - name: Update yarn.lock
        run: node ./scripts/update-package-versions.js